//<script type="text/javascript">

Pman.Readers.Companies = {
	root : 'data',
	totalProperty : 'total',
	id : 'id',
	xtype : 'JsonReader',
	fields : [
		'code',
		'name',
		'remarks',
		{name : 'owner_id',type : 'int'},
		'address',
		'tel',
		'fax',
		'email',
		{name : 'id',type : 'int'},
		{name : 'isOwner',type : 'int'},
		{name : 'logo_id',type : 'int'},
		'background_color',
		'comptype',
		'ava_craft',
		'url',
		{name : 'main_office_id',type : 'int'},
		{name : 'created_by',type : 'int'},
		{name : 'created_dt',type : 'date',dateFormat : 'Y-m-d H:i:s'},
		{name : 'updated_by',type : 'int'},
		{name : 'updated_dt',type : 'date',dateFormat : 'Y-m-d H:i:s'},
		'passwd',
		{name : 'logo_id_id',type : 'int'},
		'logo_id_filename',
		'logo_id_ontable',
		{name : 'logo_id_onid',type : 'int'},
		'logo_id_mimetype',
		{name : 'logo_id_width',type : 'int'},
		{name : 'logo_id_height',type : 'int'},
		{name : 'logo_id_filesize',type : 'int'},
		{name : 'logo_id_displayorder',type : 'int'},
		'logo_id_language',
		{name : 'logo_id_parent_image_id',type : 'int'},
		{name : 'logo_id_created',type : 'date',dateFormat : 'Y-m-d H:i:s'},
		'logo_id_imgtype',
		'logo_id_linkurl',
		'logo_id_descript',
		'logo_id_title',
		{name : 'owner_id_id',type : 'int'},
		{name : 'owner_id_office_id',type : 'int'},
		'owner_id_name',
		'owner_id_phone',
		'owner_id_fax',
		'owner_id_email',
		{name : 'owner_id_company_id',type : 'int'},
		'owner_id_role',
		{name : 'owner_id_active',type : 'int'},
		'owner_id_remarks',
		'owner_id_passwd',
		{name : 'owner_id_owner_id',type : 'int'},
		'owner_id_lang',
		{name : 'owner_id_no_reset_sent',type : 'int'},
		{name : 'owner_id_project_id',type : 'int'},
		'owner_id_action_type',
		{name : 'main_office_id_id',type : 'int'},
		{name : 'main_office_id_company_id',type : 'int'},
		'main_office_id_name',
		'main_office_id_address',
		'main_office_id_phone',
		'main_office_id_fax',
		'main_office_id_email',
		'main_office_id_role'
	]
};

Pman.Readers.Events = {
	root : 'data',
	totalProperty : 'total',
	id : 'id',
	xtype : 'JsonReader',
	fields : [
		{name : 'id',type : 'int'},
		'person_name',
		{name : 'event_when',type : 'date',dateFormat : 'Y-m-d H:i:s'},
		'action',
		'ipaddr',
		{name : 'on_id',type : 'int'},
		'on_table',
		{name : 'person_id',type : 'int'},
		'remarks',
		{name : 'person_id_id',type : 'int'},
		{name : 'person_id_office_id',type : 'int'},
		'person_id_name',
		'person_id_phone',
		'person_id_fax',
		'person_id_email',
		{name : 'person_id_company_id',type : 'int'},
		'person_id_role',
		{name : 'person_id_active',type : 'int'},
		'person_id_remarks',
		'person_id_passwd',
		{name : 'person_id_owner_id',type : 'int'},
		'person_id_lang',
		{name : 'person_id_no_reset_sent',type : 'int'},
		{name : 'person_id_project_id',type : 'int'},
		'person_id_action_type'
	]
};

Pman.Readers.Group_Members = {
	root : 'data',
	totalProperty : 'total',
	id : 'id',
	xtype : 'JsonReader',
	fields : [
		{name : 'group_id',type : 'int'},
		{name : 'id',type : 'int'},
		{name : 'user_id',type : 'int'},
		{name : 'group_id_id',type : 'int'},
		'group_id_name',
		{name : 'group_id_type',type : 'int'},
		{name : 'group_id_leader',type : 'int'},
		{name : 'user_id_id',type : 'int'},
		{name : 'user_id_office_id',type : 'int'},
		'user_id_name',
		'user_id_phone',
		'user_id_fax',
		'user_id_email',
		{name : 'user_id_company_id',type : 'int'},
		'user_id_role',
		{name : 'user_id_active',type : 'int'},
		'user_id_remarks',
		'user_id_passwd',
		{name : 'user_id_owner_id',type : 'int'},
		'user_id_lang',
		{name : 'user_id_no_reset_sent',type : 'int'},
		{name : 'user_id_project_id',type : 'int'},
		'user_id_action_type'
	]
};

Pman.Readers.Group_Rights = {
	root : 'data',
	totalProperty : 'total',
	id : 'id',
	xtype : 'JsonReader',
	fields : [
		'rightname',
		{name : 'group_id',type : 'int'},
		'accessmask',
		{name : 'id',type : 'int'},
		{name : 'group_id_id',type : 'int'},
		'group_id_name',
		{name : 'group_id_type',type : 'int'},
		{name : 'group_id_leader',type : 'int'}
	]
};

Pman.Readers.Groups = {
	root : 'data',
	totalProperty : 'total',
	id : 'id',
	xtype : 'JsonReader',
	fields : [
		{name : 'id',type : 'int'},
		'name',
		{name : 'type',type : 'int'},
		{name : 'leader',type : 'int'},
		{name : 'leader_id',type : 'int'},
		{name : 'leader_office_id',type : 'int'},
		'leader_name',
		'leader_phone',
		'leader_fax',
		'leader_email',
		{name : 'leader_company_id',type : 'int'},
		'leader_role',
		{name : 'leader_active',type : 'int'},
		'leader_remarks',
		'leader_passwd',
		{name : 'leader_owner_id',type : 'int'},
		'leader_lang',
		{name : 'leader_no_reset_sent',type : 'int'},
		{name : 'leader_project_id',type : 'int'},
		'leader_action_type'
	]
};

Pman.Readers.Images = {
	root : 'data',
	totalProperty : 'total',
	id : 'id',
	xtype : 'JsonReader',
	fields : [
		{name : 'id',type : 'int'},
		'filename',
		'ontable',
		{name : 'onid',type : 'int'},
		'mimetype',
		{name : 'width',type : 'int'},
		{name : 'height',type : 'int'},
		{name : 'filesize',type : 'int'},
		{name : 'displayorder',type : 'int'},
		'language',
		{name : 'parent_image_id',type : 'int'},
		{name : 'created',type : 'date',dateFormat : 'Y-m-d H:i:s'},
		'imgtype',
		'linkurl',
		'descript',
		'title',
		{name : 'parent_image_id_id',type : 'int'},
		'parent_image_id_filename',
		'parent_image_id_ontable',
		{name : 'parent_image_id_onid',type : 'int'},
		'parent_image_id_mimetype',
		{name : 'parent_image_id_width',type : 'int'},
		{name : 'parent_image_id_height',type : 'int'},
		{name : 'parent_image_id_filesize',type : 'int'},
		{name : 'parent_image_id_displayorder',type : 'int'},
		'parent_image_id_language',
		{name : 'parent_image_id_parent_image_id',type : 'int'},
		{name : 'parent_image_id_created',type : 'date',dateFormat : 'Y-m-d H:i:s'},
		'parent_image_id_imgtype',
		'parent_image_id_linkurl',
		'parent_image_id_descript',
		'parent_image_id_title'
	]
};

Pman.Readers.Office = {
	root : 'data',
	totalProperty : 'total',
	id : 'id',
	xtype : 'JsonReader',
	fields : [
		{name : 'id',type : 'int'},
		{name : 'company_id',type : 'int'},
		'name',
		'address',
		'phone',
		'fax',
		'email',
		'role',
		'company_id_code',
		'company_id_name',
		'company_id_remarks',
		{name : 'company_id_owner_id',type : 'int'},
		'company_id_address',
		'company_id_tel',
		'company_id_fax',
		'company_id_email',
		{name : 'company_id_id',type : 'int'},
		{name : 'company_id_isOwner',type : 'int'},
		{name : 'company_id_logo_id',type : 'int'},
		'company_id_background_color',
		'company_id_comptype',
		'company_id_ava_craft',
		'company_id_url',
		{name : 'company_id_main_office_id',type : 'int'},
		{name : 'company_id_created_by',type : 'int'},
		{name : 'company_id_created_dt',type : 'date',dateFormat : 'Y-m-d H:i:s'},
		{name : 'company_id_updated_by',type : 'int'},
		{name : 'company_id_updated_dt',type : 'date',dateFormat : 'Y-m-d H:i:s'},
		'company_id_passwd'
	]
};

Pman.Readers.Person = {
	root : 'data',
	totalProperty : 'total',
	id : 'id',
	xtype : 'JsonReader',
	fields : [
		{name : 'id',type : 'int'},
		{name : 'office_id',type : 'int'},
		'name',
		'phone',
		'fax',
		'email',
		{name : 'company_id',type : 'int'},
		'role',
		{name : 'active',type : 'int'},
		'remarks',
		'passwd',
		{name : 'owner_id',type : 'int'},
		'lang',
		{name : 'no_reset_sent',type : 'int'},
		{name : 'project_id',type : 'int'},
		'action_type',
		{name : 'office_id_id',type : 'int'},
		{name : 'office_id_company_id',type : 'int'},
		'office_id_name',
		'office_id_address',
		'office_id_phone',
		'office_id_fax',
		'office_id_email',
		'office_id_role',
		'company_id_code',
		'company_id_name',
		'company_id_remarks',
		{name : 'company_id_owner_id',type : 'int'},
		'company_id_address',
		'company_id_tel',
		'company_id_fax',
		'company_id_email',
		{name : 'company_id_id',type : 'int'},
		{name : 'company_id_isOwner',type : 'int'},
		{name : 'company_id_logo_id',type : 'int'},
		'company_id_background_color',
		'company_id_comptype',
		'company_id_ava_craft',
		'company_id_url',
		{name : 'company_id_main_office_id',type : 'int'},
		{name : 'company_id_created_by',type : 'int'},
		{name : 'company_id_created_dt',type : 'date',dateFormat : 'Y-m-d H:i:s'},
		{name : 'company_id_updated_by',type : 'int'},
		{name : 'company_id_updated_dt',type : 'date',dateFormat : 'Y-m-d H:i:s'},
		'company_id_passwd',
		{name : 'project_id_id',type : 'int'},
		'project_id_name',
		'project_id_remarks',
		{name : 'project_id_owner_id',type : 'int'},
		'project_id_code',
		{name : 'project_id_active',type : 'int'},
		'project_id_type',
		{name : 'project_id_client_id',type : 'int'},
		{name : 'project_id_team_id',type : 'int'},
		'project_id_file_location',
		{name : 'project_id_open_date',type : 'date',dateFormat : 'Y-m-d'},
		{name : 'project_id_open_by',type : 'int'},
		'project_id_countries',
		'project_id_languages',
		{name : 'project_id_close_date',type : 'date',dateFormat : 'Y-m-d'},
		{name : 'project_id_agency_id',type : 'int'},
		{name : 'owner_id_id',type : 'int'},
		{name : 'owner_id_office_id',type : 'int'},
		'owner_id_name',
		'owner_id_phone',
		'owner_id_fax',
		'owner_id_email',
		{name : 'owner_id_company_id',type : 'int'},
		'owner_id_role',
		{name : 'owner_id_active',type : 'int'},
		'owner_id_remarks',
		'owner_id_passwd',
		{name : 'owner_id_owner_id',type : 'int'},
		'owner_id_lang',
		{name : 'owner_id_no_reset_sent',type : 'int'},
		{name : 'owner_id_project_id',type : 'int'},
		'owner_id_action_type'
	]
};

Pman.Readers.Projects = {
	root : 'data',
	totalProperty : 'total',
	id : 'id',
	xtype : 'JsonReader',
	fields : [
		{name : 'id',type : 'int'},
		'name',
		'remarks',
		{name : 'owner_id',type : 'int'},
		'code',
		{name : 'active',type : 'int'},
		'type',
		{name : 'client_id',type : 'int'},
		{name : 'team_id',type : 'int'},
		'file_location',
		{name : 'open_date',type : 'date',dateFormat : 'Y-m-d'},
		{name : 'open_by',type : 'int'},
		'countries',
		'languages',
		{name : 'close_date',type : 'date',dateFormat : 'Y-m-d'},
		{name : 'agency_id',type : 'int'},
		'client_id_code',
		'client_id_name',
		'client_id_remarks',
		{name : 'client_id_owner_id',type : 'int'},
		'client_id_address',
		'client_id_tel',
		'client_id_fax',
		'client_id_email',
		{name : 'client_id_id',type : 'int'},
		{name : 'client_id_isOwner',type : 'int'},
		{name : 'client_id_logo_id',type : 'int'},
		'client_id_background_color',
		'client_id_comptype',
		'client_id_ava_craft',
		'client_id_url',
		{name : 'client_id_main_office_id',type : 'int'},
		{name : 'client_id_created_by',type : 'int'},
		{name : 'client_id_created_dt',type : 'date',dateFormat : 'Y-m-d H:i:s'},
		{name : 'client_id_updated_by',type : 'int'},
		{name : 'client_id_updated_dt',type : 'date',dateFormat : 'Y-m-d H:i:s'},
		'client_id_passwd',
		'agency_id_code',
		'agency_id_name',
		'agency_id_remarks',
		{name : 'agency_id_owner_id',type : 'int'},
		'agency_id_address',
		'agency_id_tel',
		'agency_id_fax',
		'agency_id_email',
		{name : 'agency_id_id',type : 'int'},
		{name : 'agency_id_isOwner',type : 'int'},
		{name : 'agency_id_logo_id',type : 'int'},
		'agency_id_background_color',
		'agency_id_comptype',
		'agency_id_ava_craft',
		'agency_id_url',
		{name : 'agency_id_main_office_id',type : 'int'},
		{name : 'agency_id_created_by',type : 'int'},
		{name : 'agency_id_created_dt',type : 'date',dateFormat : 'Y-m-d H:i:s'},
		{name : 'agency_id_updated_by',type : 'int'},
		{name : 'agency_id_updated_dt',type : 'date',dateFormat : 'Y-m-d H:i:s'},
		'agency_id_passwd',
		{name : 'team_id_id',type : 'int'},
		'team_id_name',
		{name : 'team_id_type',type : 'int'},
		{name : 'team_id_leader',type : 'int'},
		{name : 'open_by_id',type : 'int'},
		{name : 'open_by_office_id',type : 'int'},
		'open_by_name',
		'open_by_phone',
		'open_by_fax',
		'open_by_email',
		{name : 'open_by_company_id',type : 'int'},
		'open_by_role',
		{name : 'open_by_active',type : 'int'},
		'open_by_remarks',
		'open_by_passwd',
		{name : 'open_by_owner_id',type : 'int'},
		'open_by_lang',
		{name : 'open_by_no_reset_sent',type : 'int'},
		{name : 'open_by_project_id',type : 'int'},
		'open_by_action_type',
		{name : 'owner_id_id',type : 'int'},
		{name : 'owner_id_office_id',type : 'int'},
		'owner_id_name',
		'owner_id_phone',
		'owner_id_fax',
		'owner_id_email',
		{name : 'owner_id_company_id',type : 'int'},
		'owner_id_role',
		{name : 'owner_id_active',type : 'int'},
		'owner_id_remarks',
		'owner_id_passwd',
		{name : 'owner_id_owner_id',type : 'int'},
		'owner_id_lang',
		{name : 'owner_id_no_reset_sent',type : 'int'},
		{name : 'owner_id_project_id',type : 'int'},
		'owner_id_action_type'
	]
};

Pman.Readers.I18n = {
	root : 'data',
	totalProperty : 'total',
	id : 'id',
	xtype : 'JsonReader',
	fields : [
		{name : 'id',type : 'int'},
		'ltype',
		'lkey',
		'inlang',
		'lval'
	]
};

Pman.Readers.Proftp_groups = {
	root : 'data',
	totalProperty : 'total',
	id : 'id',
	xtype : 'JsonReader',
	fields : [
		{name : 'id',type : 'int'},
		{name : 'grpid',type : 'int'},
		'grpname',
		'grpmembers'
	]
};

Pman.Readers.Translations = {
	root : 'data',
	totalProperty : 'total',
	id : 'id',
	xtype : 'JsonReader',
	fields : [
		{name : 'id',type : 'int'},
		'module',
		'tfile',
		'tlang',
		'tkey',
		'tval'
	]
};
